#! /bin/sh

OS=`uname`; export OS
case "$OS" in
[Ll]inux)
  echo "Compiling for Linux"
  g++ -I/usr/include/nptl -pipe -O3 -fPIC -finline-limit=20000 -fkeep-inline-functions -finline-functions -ffast-math -fomit-frame-pointer -DNDEBUG -I. -I../../heaplayers -I../../heaplayers/util -DUSE_HOARD=1 -D_REENTRANT=1 -c libhoard.cpp
  g++ -shared libhoard.o -lpthread -o libhoard.so -ldl;;
SunOS)
  echo "Compiling for Solaris"
  g++ -nostartfiles -pipe -DNDEBUG -mcpu=ultrasparc -O3 -finline-limit=20000 -fPIC -fkeep-inline-functions -finline-functions -ffast-math -fomit-frame-pointer -I. -I../../heaplayers -I../../heaplayers/util -DUSE_HOARD=1 -D_REENTRANT=1 -shared libhoard.cpp -lthread -lpthread -ldl -o libhoard.so;;
*)
case "$OSTYPE" in
[Dd]arwin8.0)
echo "Compiling for Darwin"
  g++ -pipe -O3 -fkeep-inline-functions -finline-functions -ffast-math -fomit-frame-pointer -DNDEBUG  -I. -I../../heaplayers -I../../heaplayers/util -D_REENTRANT=1 -compatibility_version 1 -current_version 1 -dynamiclib libhoard.cpp -o libhoard.dylib;;
*)
  echo "Compile script not supported for this OS."
esac
esac



