#! /bin/sh

case "$OSTYPE" in
linux)
  echo "Compiling for Linux"
  g++ -pipe -mcpu=pentiumpro -O3 -finline-limit=5000 -fkeep-inline-functions -finline-functions -ffast-math -fomit-frame-pointer -DNDEBUG -I. -I../../heaplayers -DUSE_HOARD=1 -D_REENTRANT=1 -nostartfiles -c libhoard.cpp
  g++ -shared libhoard.o -lpthread -o libhoard.so;;
solaris)
  echo "Compiling for Solaris"
  g++ -pipe -DNDEBUG -mcpu=ultrasparc -O3 -finline-limit=20000 -fPIC -fkeep-inline-functions -finline-functions -ffast-math -fomit-frame-pointer -I. -I../../heaplayers -DUSE_HOARD=1 -D_REENTRANT=1 -shared libhoard.cpp -lthread -lpthread -o libhoard.so;;
*)
  echo "hmmm"
esac



