// Hoard version 3.5.0 = 30500

#define HOARD_MAJOR 3
#define HOARD_MINOR 5
#define HOARD_PATCH 0

#define HOARD_VERSION_STRING "3.5.0"
#define HOARD_VERSION_NUMBER (HOARD_MAJOR * 10000 + HOARD_MINOR * 100 + HOARD_PATCH)
