#line 2 "libpbcompiler_a-pblexer.cpp"

#line 4 "libpbcompiler_a-pblexer.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer pb_create_buffer
#define yy_delete_buffer pb_delete_buffer
#define yy_flex_debug pb_flex_debug
#define yy_init_buffer pb_init_buffer
#define yy_flush_buffer pb_flush_buffer
#define yy_load_buffer_state pb_load_buffer_state
#define yy_switch_to_buffer pb_switch_to_buffer
#define yyin pbin
#define yyleng pbleng
#define yylex pblex
#define yylineno pblineno
#define yyout pbout
#define yyrestart pbrestart
#define yytext pbtext
#define yywrap pbwrap
#define yyalloc pballoc
#define yyrealloc pbrealloc
#define yyfree pbfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE pbrestart(pbin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int pbleng;

extern FILE *pbin, *pbout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE pblex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-pblineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < pbleng; ++yyl )\
                    if ( pbtext[yyl] == '\n' )\
                        --pblineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up pbtext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up pbtext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via pbrestart()), so that the user can continue scanning by
	 * just pointing pbin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when pbtext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int pbleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow pbwrap()'s to do buffer switches
 * instead of setting up a fresh pbin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void pbrestart (FILE *input_file  );
void pb_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE pb_create_buffer (FILE *file,int size  );
void pb_delete_buffer (YY_BUFFER_STATE b  );
void pb_flush_buffer (YY_BUFFER_STATE b  );
void pbpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void pbpop_buffer_state (void );

static void pbensure_buffer_stack (void );
static void pb_load_buffer_state (void );
static void pb_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER pb_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE pb_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE pb_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE pb_scan_bytes (yyconst char *bytes,int len  );

void *pballoc (yy_size_t  );
void *pbrealloc (void *,yy_size_t  );
void pbfree (void *  );

#define yy_new_buffer pb_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        pbensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            pb_create_buffer(pbin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        pbensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            pb_create_buffer(pbin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define pbwrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *pbin = (FILE *) 0, *pbout = (FILE *) 0;

typedef int yy_state_type;

extern int pblineno;

int pblineno = 1;

extern char *pbtext;
#define yytext_ptr pbtext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up pbtext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	pbleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 68
#define YY_END_OF_BUFFER 69
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[286] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   17,   17,   69,   67,   66,   66,   67,   67,
       45,   45,   45,   45,   41,   45,   45,   45,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   15,
       67,   48,   44,   44,   44,   44,   44,   44,   44,   28,
       29,   55,   55,   55,   53,   56,   56,   52,   54,   51,
       58,   58,   58,   59,   58,   61,   61,   60,   61,   63,
       63,   63,   62,   63,   63,   17,   17,   17,   67,   17,
       16,   37,    0,    0,    0,   46,   47,    0,   41,   34,
       36,   35,   44,   44,   44,   44,   44,   44,   44,   44,

       44,   40,   44,   44,   44,   30,   44,   44,   44,   39,
        0,   44,   44,   44,   44,   44,   44,   44,   55,   49,
       50,   55,   58,   57,   58,   61,   61,   64,   17,   18,
       19,   17,    0,   43,   42,   44,   38,   44,   44,    6,
       44,   44,   44,   44,   44,   44,   44,   44,   44,    0,
       44,   44,   44,   44,   44,   44,   44,   55,   58,   61,
       17,   44,   44,   31,   44,   44,    1,   44,   44,   44,
       44,   44,   44,   44,   65,   44,   44,   44,   44,   44,
       27,   44,   44,   55,   58,   61,   17,   44,   44,   44,
       44,   44,    8,   44,   44,   44,   44,   32,   65,   44,

       44,   44,   44,   44,   44,   20,   55,   58,   61,   17,
       44,    7,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   33,   44,   10,   44,   22,   44,   44,   44,
       44,   44,   44,   44,    2,   44,    4,   44,   44,   21,
       44,   44,   44,   44,    5,   44,    9,    3,   26,   25,
       24,   23,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   12,   44,   44,   14,   44,   44,
       11,   44,   44,   13,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    1,    7,    8,    1,    9,
        9,   10,   11,    9,   11,   12,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,    1,    1,   15,
       16,   17,    1,    1,   18,   18,   18,   18,   19,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
        9,   20,    9,    9,   21,    1,   22,   23,   24,   25,

       26,   27,   28,   29,   30,   18,   18,   31,   32,   33,
       34,   35,   18,   36,   37,   38,   39,   40,   41,   18,
       42,   43,   44,   45,   46,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[47] =
    {   0,
        1,    1,    2,    1,    3,    1,    4,    1,    1,    5,
        1,    1,    3,    6,    1,    1,    1,    6,    6,    1,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    3,    1,    3
    } ;

static yyconst flex_int16_t yy_base[302] =
    {   0,
        0,  442,   40,  441,   85,  130,   46,   49,   89,   97,
      102,  106,  111,  117,  446,  449,  449,  449,  401,  436,
      449,   46,  125,   44,  133,  427,  426,  425,    0,   47,
      406,  403,  412,  404,   41,  400,  413,  124,  397,  449,
      388,  428,  398,  391,  393,   35,  402,   68,  398,  449,
      449,    0,    0,    0,  449,  449,   69,  449,  449,  422,
        0,    0,    0,  412,  420,    0,    0,  449,  419,  449,
      449,  449,  449,  417,  417,    0,    0,    0,  374,  415,
      449,  449,  142,  143,  114,  449,  449,  152,  153,  449,
      449,  449,    0,  394,  392,  383,  381,  381,  378,  382,

      379,    0,  374,  377,  372,    0,  385,  373,  375,  449,
      390,  368,  372,  377,  362,  368,  374,  371,    0,  449,
      449,  382,    0,  449,  381,    0,  380,  449,    0,  449,
      449,  379,  378,  377,  161,  351,    0,  362,  356,  361,
      347,  352,  350,  361,  347,  347,  347,  357,  345,   69,
      346,   62,  337,  353,  348,  339,  336,  113,  134,  177,
      178,  335,  340,    0,  333,  330,    0,  337,  334,  334,
      325,  326,  339,  333,    0,  330,  337,  322,  321,  318,
        0,  322,  328,  180,  139,    0,  181,  331,  324,  329,
      329,  306,  322,  325,  318,  318,  313,    0,    0,  319,

      306,  311,  303,  317,  313,    0,  191,  167,    0,  192,
      313,    0,  298,  308,  308,  295,  294,  302,  296,  303,
      306,  275,  261,  259,  258,  256,  230,  236,  210,  209,
      207,  206,    0,  195,    0,  192,    0,  187,  188,  196,
      189,  202,  186,  199,    0,  184,    0,  187,  192,    0,
      191,  190,  173,  166,    0,  176,    0,    0,    0,    0,
        0,    0,  183,  186,  189,  171,  176,  170,  171,  169,
      166,  166,  170,  171,    0,  156,  124,    0,  117,  107,
        0,   85,   59,    0,  449,  237,  243,  249,  255,  261,
       60,  267,  273,  279,  285,  291,  297,  303,  309,  315,

      321
    } ;

static yyconst flex_int16_t yy_def[302] =
    {   0,
      285,    1,    1,    3,  286,  286,  287,  287,  288,  288,
      289,  289,  290,  290,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  285,
      285,  285,  291,  291,  291,  291,  291,  291,  291,  285,
      285,  292,  292,  292,  285,  285,  285,  285,  285,  292,
      293,  293,  293,  285,  293,  294,  294,  285,  294,  285,
      285,  285,  285,  285,  285,  295,  295,  295,  296,  295,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  291,  291,  291,  291,  291,  291,  291,  291,

      291,  291,  291,  291,  291,  291,  291,  291,  291,  285,
      285,  291,  291,  291,  291,  291,  291,  291,  292,  285,
      285,  292,  293,  285,  293,  294,  294,  285,  295,  285,
      285,  295,  285,  285,  285,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  285,
      291,  291,  291,  291,  291,  291,  291,  292,  293,  294,
      295,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  297,  291,  291,  291,  291,  291,
      291,  291,  291,  298,  299,  300,  301,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  297,  291,

      291,  291,  291,  291,  291,  291,  298,  299,  300,  301,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,    0,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,

      285
    } ;

static yyconst flex_int16_t yy_nxt[496] =
    {   0,
       16,   17,   18,   17,   16,   16,   19,   20,   21,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   29,   16,
       29,   30,   29,   31,   29,   29,   32,   33,   29,   34,
       29,   35,   29,   36,   37,   29,   29,   38,   39,   29,
       29,   29,   29,   40,   41,   16,   16,   62,   63,   62,
       62,   63,   62,   86,   65,   64,   87,   83,   64,   84,
      114,   43,  100,   29,   44,   93,  101,   29,  115,   29,
       94,   29,  175,  116,   45,   46,   47,   48,  120,   95,
       49,  121,  150,   50,  284,   51,   53,   54,   53,   55,
       67,   68,   67,  177,   56,  178,  105,   57,   67,   68,

       67,  106,   69,   71,   72,   71,   73,   71,   72,   71,
       73,   75,   77,   78,   77,  283,  184,   79,   77,   78,
       77,   74,   80,   79,  133,   74,  158,  134,   58,  282,
       59,   53,   54,   53,   55,   60,   83,  185,   83,   56,
      281,  123,   57,   85,   88,  280,   89,  159,  199,  104,
       85,   85,  105,   83,   88,   83,   84,  106,   85,  107,
       85,   85,  108,   83,   88,  135,   89,   85,   85,  123,
       85,   85,   83,   58,  135,   59,  199,   85,   85,   85,
      186,  187,  119,  129,  199,  279,   85,  199,  263,  199,
      160,  161,  199,  119,  129,  199,  278,  264,  199,  277,

      199,  276,  275,  199,  274,  265,  273,  272,  271,  270,
      269,  268,  267,  266,  262,  261,  260,  259,  258,  257,
      256,  255,  254,  199,  253,  199,  252,  251,  250,  249,
      248,  247,  246,  245,  199,  244,  199,   52,   52,   52,
       52,   52,   52,   61,   61,   61,   61,   61,   61,   66,
       66,   66,   66,   66,   66,   70,   70,   70,   70,   70,
       70,   76,   76,   76,   76,   76,   76,  119,  119,  243,
      119,  242,  119,  123,  123,  123,  123,  241,  123,  126,
      240,  126,  126,  126,  126,  129,  129,  129,  239,  129,
      129,  130,  130,  130,  130,  130,  130,  199,  238,  199,

      199,  199,  199,  207,  207,  207,  207,  207,  207,  208,
      208,  208,  208,  208,  208,  209,  237,  209,  209,  209,
      209,  210,  210,  210,  210,  210,  210,  236,  235,  234,
      233,  232,  231,  230,  229,  228,  227,  226,  225,  224,
      223,  222,  221,  220,  219,  218,  217,  216,  215,  214,
      213,  212,  211,  206,  205,  204,  203,  202,  201,  200,
      198,  197,  196,  195,  194,  193,  192,  191,  190,  189,
      188,  183,  182,  181,  180,  179,  176,  174,  173,  172,
      171,  170,  169,  168,  167,  166,  165,  164,  163,  162,
      134,  134,  161,  160,  159,  158,  157,  156,  155,  154,

      153,  152,  151,  150,  149,  148,  147,  146,  145,  144,
      143,  142,  141,  140,  139,  138,  137,  136,  132,  131,
      111,  128,  127,  125,  124,  122,  118,  117,  113,  112,
       95,  111,  110,  109,  103,  102,   99,   98,   97,   96,
       92,   91,   90,   82,   81,  285,   42,   42,   15,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285

    } ;

static yyconst flex_int16_t yy_chk[496] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    7,    7,    7,
        8,    8,    8,   24,    8,    7,   24,   22,    8,   22,
       46,    3,   35,    3,    3,  291,   35,    3,   46,    3,
       30,    3,  150,   46,    3,    3,    3,    3,   57,   30,
        3,   57,  150,    3,  283,    3,    5,    5,    5,    5,
        9,    9,    9,  152,    5,  152,   48,    5,   10,   10,

       10,   48,   10,   11,   11,   11,   11,   12,   12,   12,
       12,   12,   13,   13,   13,  282,  158,   13,   14,   14,
       14,   11,   14,   14,   85,   12,  158,   85,    5,  280,
        5,    6,    6,    6,    6,    6,   23,  159,   23,    6,
      279,  185,    6,   23,   25,  277,   25,  159,  185,   38,
       23,   25,   38,   83,   84,   83,   84,   38,   25,   38,
       83,   84,   38,   88,   89,   88,   89,   83,   84,  208,
       88,   89,  135,    6,  135,    6,  208,   88,   89,  135,
      160,  161,  184,  187,  184,  276,  135,  187,  254,  184,
      160,  161,  184,  207,  210,  207,  274,  254,  210,  273,

      207,  272,  271,  207,  270,  254,  269,  268,  267,  266,
      265,  264,  263,  256,  253,  252,  251,  249,  248,  246,
      244,  243,  242,  184,  241,  184,  240,  239,  238,  236,
      234,  232,  231,  230,  207,  229,  207,  286,  286,  286,
      286,  286,  286,  287,  287,  287,  287,  287,  287,  288,
      288,  288,  288,  288,  288,  289,  289,  289,  289,  289,
      289,  290,  290,  290,  290,  290,  290,  292,  292,  228,
      292,  227,  292,  293,  293,  293,  293,  226,  293,  294,
      225,  294,  294,  294,  294,  295,  295,  295,  224,  295,
      295,  296,  296,  296,  296,  296,  296,  297,  223,  297,

      297,  297,  297,  298,  298,  298,  298,  298,  298,  299,
      299,  299,  299,  299,  299,  300,  222,  300,  300,  300,
      300,  301,  301,  301,  301,  301,  301,  221,  220,  219,
      218,  217,  216,  215,  214,  213,  211,  205,  204,  203,
      202,  201,  200,  197,  196,  195,  194,  193,  192,  191,
      190,  189,  188,  183,  182,  180,  179,  178,  177,  176,
      174,  173,  172,  171,  170,  169,  168,  166,  165,  163,
      162,  157,  156,  155,  154,  153,  151,  149,  148,  147,
      146,  145,  144,  143,  142,  141,  140,  139,  138,  136,
      134,  133,  132,  127,  125,  122,  118,  117,  116,  115,

      114,  113,  112,  111,  109,  108,  107,  105,  104,  103,
      101,  100,   99,   98,   97,   96,   95,   94,   80,   79,
       75,   74,   69,   65,   64,   60,   49,   47,   45,   44,
       43,   42,   41,   39,   37,   36,   34,   33,   32,   31,
       28,   27,   26,   20,   19,   15,    4,    2,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285

    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[69] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 
    1, 0, 0, 1, 0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int pb_flex_debug;
int pb_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *pbtext;
#line 1 "pblexer.lpp"
/*****************************************************************************
 *  Copyright (C) 2008-2011 Massachusetts Institute of Technology            *
 *                                                                           *
 *  Permission is hereby granted, free of charge, to any person obtaining    *
 *  a copy of this software and associated documentation files (the          *
 *  "Software"), to deal in the Software without restriction, including      *
 *  without limitation the rights to use, copy, modify, merge, publish,      *
 *  distribute, sublicense, and/or sell copies of the Software, and to       *
 *  permit persons to whom the Software is furnished to do so, subject       *
 *  to the following conditions:                                             *
 *                                                                           *
 *  The above copyright notice and this permission notice shall be included  *
 *  in all copies or substantial portions of the Software.                   *
 *                                                                           *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY                *
 *  KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE               *
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND      *
 *  NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE   *
 *  LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION   *
 *  OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION    *
 *  WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE           *
 *                                                                           *
 *  This source code is part of the PetaBricks project:                      *
 *    http://projects.csail.mit.edu/petabricks/                              *
 *                                                                           *
 *****************************************************************************/
#line 39 "pblexer.lpp"

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wunused-but-set-variable"
#pragma GCC diagnostic ignored "-Warray-bounds"
#endif

#include "codegenerator.h"
#include "formula.h"
#include "matrixdef.h"
#include "transform.h"
#include "userrule.h"

#include "common/jassert.h"
#include "common/jconvert.h"
#include "common/srcpos.h"

#include <stdio.h>
#include <string>
#include <string.h>
#include <sstream>

#include "pbparser.h"

using namespace std;

void pbparser_addRefPoolItem(jalib::JRefCounted* i);//pbparser.ypp

static std::stringstream theParseLog;

static const char* allocPoolString(const char* str){
  struct StrStorage : public std::string, public jalib::JRefCounted {
    StrStorage(const char* s) : std::string(s) {}
  };
  StrStorage* s = new StrStorage(str);
  pbparser_addRefPoolItem(s);
  return s->c_str();
}

static void recordLitCode(){
  std::string str = theParseLog.str().c_str();
  theParseLog.str("");
  petabricks::CodeGenerator::theFilePrefix() << std::string(str.begin(), str.end()-2);
}

std::string pbfilename;
int rulebodystart=0;
int pbcolno=0;
int pblastlineno=-1;

static void handleCppLine(const char* s){
  const char* n_begin = s+2;
  const char* n_end = n_begin;
  while(*n_end>='0' && *n_end<='9') ++n_end;
  const char* filename=n_end+1;
  std::string n(n_begin, n_end);
  //JTRACE("LINENO")(n)(filename);
  pblineno = jalib::StringToInt(n)-1;
  pbfilename = filename;
}

#define YY_USER_ACTION \
  pblval.str=allocPoolString(pbtext);                              \
  theParseLog<<pbtext;                                             \
  SRCPOS_FILL(*yylloc, pbfilename, pblineno, pblastlineno, pbcolno)

#define RETURN theParseLog.str(""); return

static int theNestCount=0;


#line 807 "libpbcompiler_a-pblexer.cpp"

#define INITIAL 0
#define transform 1
#define rule 2
#define comment 3
#define linecomment 4
#define string 5
#define litcode 6

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int pblex_destroy (void );

int pbget_debug (void );

void pbset_debug (int debug_flag  );

YY_EXTRA_TYPE pbget_extra (void );

void pbset_extra (YY_EXTRA_TYPE user_defined  );

FILE *pbget_in (void );

void pbset_in  (FILE * in_str  );

FILE *pbget_out (void );

void pbset_out  (FILE * out_str  );

int pbget_leng (void );

char *pbget_text (void );

int pbget_lineno (void );

void pbset_lineno (int line_number  );

YYSTYPE * pbget_lval (void );

void pbset_lval (YYSTYPE * yylval_param  );

       YYLTYPE *pbget_lloc (void );
    
        void pbset_lloc (YYLTYPE * yylloc_param  );
    
/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int pbwrap (void );
#else
extern int pbwrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

        static int yy_start_stack_ptr = 0;
        static int yy_start_stack_depth = 0;
        static int *yy_start_stack = NULL;
    
    static void yy_push_state (int new_state );
    
    static void yy_pop_state (void );
    
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( pbtext, pbleng, 1, pbout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( pbin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( pbin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, pbin))==0 && ferror(pbin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(pbin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int pblex \
               (YYSTYPE * yylval_param,YYLTYPE * yylloc_param );

#define YY_DECL int pblex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param )
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after pbtext and pbleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( pbleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(pbtext[pbleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
        YYSTYPE * yylval;
    
        YYLTYPE * yylloc;
    
#line 114 "pblexer.lpp"

#line 1025 "libpbcompiler_a-pblexer.cpp"

    yylval = yylval_param;

    yylloc = yylloc_param;

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! pbin )
			pbin = stdin;

		if ( ! pbout )
			pbout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			pbensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				pb_create_buffer(pbin,YY_BUF_SIZE );
		}

		pb_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of pbtext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 286 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 449 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < pbleng; ++yyl )
				if ( pbtext[yyl] == '\n' )
					   
    pblineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 116 "pblexer.lpp"
RETURN KW_MAIN;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 117 "pblexer.lpp"
RETURN KW_MEMOIZED;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 118 "pblexer.lpp"
RETURN KW_TRANSFORM;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 119 "pblexer.lpp"
RETURN KW_TEMPLATE;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 120 "pblexer.lpp"
RETURN KW_GENERATOR;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 121 "pblexer.lpp"
RETURN KW_GENERATOR;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 122 "pblexer.lpp"
RETURN KW_CONFIG;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 123 "pblexer.lpp"
RETURN KW_PARAM;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 124 "pblexer.lpp"
RETURN KW_PARAM;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 125 "pblexer.lpp"
RETURN KW_TUNABLE;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 126 "pblexer.lpp"
RETURN KW_ACCURACYMETRIC;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 127 "pblexer.lpp"
RETURN KW_ACCURACYBINS;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 128 "pblexer.lpp"
RETURN KW_ACCURACYVARIABLE;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 129 "pblexer.lpp"
RETURN KW_INPUTFEATURE;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 130 "pblexer.lpp"
yy_push_state(transform); RETURN '{';
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 131 "pblexer.lpp"
yy_push_state(litcode); theParseLog.str("");
	YY_BREAK


case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 135 "pblexer.lpp"
/*nothing*/
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 136 "pblexer.lpp"
/*nothing*/
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 137 "pblexer.lpp"
{
      yy_pop_state();
      recordLitCode();
  }
	YY_BREAK


case 20:
YY_RULE_SETUP
#line 144 "pblexer.lpp"
RETURN KW_WHERE;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 145 "pblexer.lpp"
RETURN KW_PRIORITY;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 146 "pblexer.lpp"
RETURN KW_PRIMARY;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 147 "pblexer.lpp"
RETURN KW_SECONDARY;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 148 "pblexer.lpp"
RETURN KW_ROTATABLE;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 149 "pblexer.lpp"
RETURN KW_RECURSIVE;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 150 "pblexer.lpp"
RETURN KW_DUPLICATE;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 151 "pblexer.lpp"
RETURN KW_RULE;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 152 "pblexer.lpp"
{
                     yy_push_state(rule); 
                     theNestCount=1; 
                     theParseLog.str("");
                     theParseLog << "# " << pblineno << " " << pbfilename << "\n";
                     return *pbtext;
                   }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 159 "pblexer.lpp"
yy_pop_state();      RETURN *pbtext;
	YY_BREAK


case 30:
YY_RULE_SETUP
#line 163 "pblexer.lpp"
RETURN KW_TO;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 164 "pblexer.lpp"
RETURN KW_FROM;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 165 "pblexer.lpp"
RETURN KW_THROUGH;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 166 "pblexer.lpp"
RETURN KW_THROUGH;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 167 "pblexer.lpp"
RETURN KW_LE;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 168 "pblexer.lpp"
RETURN KW_GE;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 169 "pblexer.lpp"
RETURN KW_EQ;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 170 "pblexer.lpp"
RETURN KW_AND;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 171 "pblexer.lpp"
RETURN KW_AND;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 172 "pblexer.lpp"
RETURN KW_OR;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 173 "pblexer.lpp"
RETURN KW_OR;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 174 "pblexer.lpp"
RETURN TOK_INTEGER;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 175 "pblexer.lpp"
RETURN TOK_FLOAT;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 176 "pblexer.lpp"
RETURN TOK_FLOAT;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 177 "pblexer.lpp"
RETURN IDENT;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 178 "pblexer.lpp"
RETURN pbtext[0];
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 179 "pblexer.lpp"
yy_push_state(comment);
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 180 "pblexer.lpp"
yy_push_state(linecomment);
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 181 "pblexer.lpp"
yy_push_state(linecomment);
	YY_BREAK


case 49:
YY_RULE_SETUP
#line 185 "pblexer.lpp"
yy_push_state(comment);
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 186 "pblexer.lpp"
yy_push_state(linecomment);
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 187 "pblexer.lpp"
yy_push_state(linecomment);
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 188 "pblexer.lpp"
++theNestCount;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 189 "pblexer.lpp"
yy_push_state(string);
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 190 "pblexer.lpp"
{ 
                      if(--theNestCount==0){
                        yy_pop_state();
                        pblval.str=allocPoolString(theParseLog.str().c_str());
                        RETURN TOK_RULEBODY;
                      }
                   }
	YY_BREAK
case 55:
/* rule 55 can match eol */
YY_RULE_SETUP
#line 197 "pblexer.lpp"
/*nothing*/
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 198 "pblexer.lpp"
/*nothing*/
	YY_BREAK


case 57:
YY_RULE_SETUP
#line 202 "pblexer.lpp"
yy_pop_state();
	YY_BREAK
case 58:
/* rule 58 can match eol */
YY_RULE_SETUP
#line 203 "pblexer.lpp"
/*nothing*/
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 204 "pblexer.lpp"
/*nothing*/
	YY_BREAK


case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 208 "pblexer.lpp"
yy_pop_state();
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 209 "pblexer.lpp"
/*nothing*/
	YY_BREAK


case 62:
YY_RULE_SETUP
#line 213 "pblexer.lpp"
yy_pop_state();
	YY_BREAK
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 214 "pblexer.lpp"
/*nothing*/
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 215 "pblexer.lpp"
/*nothing*/
	YY_BREAK


case 65:
YY_RULE_SETUP
#line 219 "pblexer.lpp"
handleCppLine(pbtext);
	YY_BREAK
case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 220 "pblexer.lpp"
/* whitespace */;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 221 "pblexer.lpp"
JASSERT(false)(pbtext)(pblineno).Text("Unhandled input");
	YY_BREAK

case 68:
YY_RULE_SETUP
#line 224 "pblexer.lpp"
ECHO;
	YY_BREAK
#line 1502 "libpbcompiler_a-pblexer.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(transform):
case YY_STATE_EOF(rule):
case YY_STATE_EOF(comment):
case YY_STATE_EOF(linecomment):
case YY_STATE_EOF(string):
case YY_STATE_EOF(litcode):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed pbin at a new source and called
			 * pblex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = pbin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( pbwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * pbtext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of pblex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					pbrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			pbrestart(pbin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) pbrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 286 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 286 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 285);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					pbrestart(pbin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( pbwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve pbtext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		   
    pblineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void pbrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        pbensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            pb_create_buffer(pbin,YY_BUF_SIZE );
	}

	pb_init_buffer(YY_CURRENT_BUFFER,input_file );
	pb_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void pb_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		pbpop_buffer_state();
	 *		pbpush_buffer_state(new_buffer);
     */
	pbensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	pb_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (pbwrap()) processing, but the only time this flag
	 * is looked at is after pbwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void pb_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	pbin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE pb_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) pballoc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in pb_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) pballoc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in pb_create_buffer()" );

	b->yy_is_our_buffer = 1;

	pb_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with pb_create_buffer()
 * 
 */
    void pb_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		pbfree((void *) b->yy_ch_buf  );

	pbfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a pbrestart() or at EOF.
 */
    static void pb_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	pb_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then pb_init_buffer was _probably_
     * called from pbrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void pb_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		pb_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void pbpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	pbensure_buffer_stack();

	/* This block is copied from pb_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from pb_switch_to_buffer. */
	pb_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void pbpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	pb_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		pb_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void pbensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)pballoc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in pbensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)pbrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in pbensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE pb_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) pballoc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in pb_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	pb_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to pblex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       pb_scan_bytes() instead.
 */
YY_BUFFER_STATE pb_scan_string (yyconst char * yystr )
{
    
	return pb_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to pblex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE pb_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) pballoc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in pb_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = pb_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in pb_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

    static void yy_push_state (int  new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) pballoc(new_size  );

		else
			(yy_start_stack) = (int *) pbrealloc((void *) (yy_start_stack),new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(new_state);
}

    static void yy_pop_state  (void)
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up pbtext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		pbtext[pbleng] = (yy_hold_char); \
		(yy_c_buf_p) = pbtext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		pbleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int pbget_lineno  (void)
{
        
    return pblineno;
}

/** Get the input stream.
 * 
 */
FILE *pbget_in  (void)
{
        return pbin;
}

/** Get the output stream.
 * 
 */
FILE *pbget_out  (void)
{
        return pbout;
}

/** Get the length of the current token.
 * 
 */
int pbget_leng  (void)
{
        return pbleng;
}

/** Get the current token.
 * 
 */

char *pbget_text  (void)
{
        return pbtext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void pbset_lineno (int  line_number )
{
    
    pblineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see pb_switch_to_buffer
 */
void pbset_in (FILE *  in_str )
{
        pbin = in_str ;
}

void pbset_out (FILE *  out_str )
{
        pbout = out_str ;
}

int pbget_debug  (void)
{
        return pb_flex_debug;
}

void pbset_debug (int  bdebug )
{
        pb_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from pblex_destroy(), so don't allocate here.
     */

    /* We do not touch pblineno unless the option is enabled. */
    pblineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_start_stack_ptr) = 0;
    (yy_start_stack_depth) = 0;
    (yy_start_stack) =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    pbin = stdin;
    pbout = stdout;
#else
    pbin = (FILE *) 0;
    pbout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * pblex_init()
     */
    return 0;
}

/* pblex_destroy is for both reentrant and non-reentrant scanners. */
int pblex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		pb_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		pbpop_buffer_state();
	}

	/* Destroy the stack itself. */
	pbfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Destroy the start condition stack. */
        pbfree((yy_start_stack)  );
        (yy_start_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * pblex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *pballoc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *pbrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void pbfree (void * ptr )
{
	free( (char *) ptr );	/* see pbrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 224 "pblexer.lpp"





